### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Maciej4535** [ufosc/AmongUs#14]
Hello! I have server on spigot and i don't know how to install this, i know how to install plugins but how to install this?

**Comment by hjarrell** [comment]
Hi sorry this project is still in very early stages of development and there is really nothing usable to install. If you were to install this you would have to build the project from source, using the Maven build tool. You would make sure you have the project cloned/downloaded to your local machine, maven installed, and you would run the command mvn package. This would generate the plugin jar in a target directory.

**Comment by Maciej4535** [comment]
Okay..

**Comment by Maciej4535** [comment]
i wait
